package com.t09g01.projeto.gui;

public enum ACTION {
        WATERGIRL_UP, WATERGIRL_DOWN, WATERGIRL_LEFT, WATERGIRL_RIGHT,
        FIREBOY_UP, FIREBOY_DOWN, FIREBOY_LEFT, FIREBOY_RIGHT,
        QUIT, NONE
}
